### ISSUE TITLE
need an example for CRD injection

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/trait-injector#3]
How could this trait injector allow user to build plugin for CRD inject?

Or how could we do when we need to add a new CRD injection for a production running trait-injector ?

**Comment by hongchaodeng** [comment]
> How could this trait injector allow user to build plugin for CRD inject?

We should provide plugin mechanism to supporting custom Source and Target.

**Comment by wonderflow** [comment]
We have already add source code level plugin mechanism, closing
